version: "2"
linters:
  default: none
  enable:
    - gocyclo
    - govet
    - misspell
    # - staticcheck // TODO: enable later once the code is properly updated
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    #- goimports // TODO: enable later once the code is properly updated
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - sigs.k8s.io/descheduler
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
