sudo: false

language: go

go:
  - 1.11.1
services:
  - docker
before_script:
  - curl -Lo kubectl \https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - wget https://github.com/kubernetes-sigs/kind/releases/download/0.2.1/kind-linux-amd64
  - chmod +x kind-linux-amd64
  - mv kind-linux-amd64 kind
  - export PATH=$PATH:$PWD
  - kind create cluster --config=$TRAVIS_BUILD_DIR/hack/kind_config.yaml
  - export KUBECONFIG="$(kind get kubeconfig-path)"
  - docker pull kubernetes/pause
  - kind load docker-image kubernetes/pause
  - cp "$(kind get kubeconfig-path --name="kind")" /tmp/admin.conf
script:
- mkdir -p ~/gopath/src/sigs.k8s.io/
- mv ~/gopath/src/github.com/kubernetes-sigs/descheduler ~/gopath/src/sigs.k8s.io/.
- hack/verify-gofmt.sh
- make lint
- make build
- make test-unit
- make test-e2e
