# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG GORUNNER_VERSION=v2.3.1-go1.18.2-bullseye.0

FROM k8s.gcr.io/build-image/go-runner:${GORUNNER_VERSION} as build-base

FROM scratch

LABEL maintainer="Kubernetes SIG Scheduling <kubernetes-sig-scheduling@googlegroups.com>"

WORKDIR /

COPY --from=build-base /go-runner /

USER 1000

COPY _output/bin/descheduler /bin/descheduler

ENTRYPOINT [ "/go-runner" ]
CMD ["/bin/descheduler", "--help"]
