kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: hack/kind/
    containerPath: /configs
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    scheduler:
      extraArgs:
        config: /configs/scheduler-configuration.yaml
      extraVolumes:
        - name: schedulerconfig
          hostPath: /configs/scheduler-configuration.yaml
          mountPath: /configs/scheduler-configuration.yaml
          readOnly: true
          pathType: "File"
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=local-a"
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=local-b"
