apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration

clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf

leaderElection:
  leaderElect: false

profiles:
  - plugins:
      score:
        disabled:
          - name: SelectorSpread
        enabled:
          - name: PodTopologySpread
            weight: 10
    pluginConfig:
      - name: PodTopologySpread
        args:
          defaultConstraints:
            - maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              whenUnsatisfiable: ScheduleAnyway
          defaultingType: List
