apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveFailedPods":
    enabled: true
    params:
      failedPods:
        reasons:
        - "OutOfcpu"
        - "CreateContainerConfigError"
        includingInitContainers: true
        excludeOwnerKinds:
        - "Job"
        minPodLifetimeSeconds: 3600 # 1 hour
