apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "RemovePodsViolatingTopologySpreadConstraint"
      args:
        includeSoftConstraints: true # Include 'ScheduleAnyways' constraints
    plugins:
      balance:
        enabled:
          - "RemovePodsViolatingTopologySpreadConstraint"
