---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
        enabled: true
        params:
          labelSelector:
            matchLabels:
              "akkeris.io/production": "false"
      "RemovePodsHavingTooManyRestarts":
        enabled: true
        params:
          podsHavingTooManyRestarts:
            podRestartThreshold: 50
            includingInitContainers: true
      "RemoveFailedPods":
        enabled: true
        excludeOwnerKinds:
        - "Job"
        params:
          labelSelector:
            matchLabels:
              "akkeris.io/production": "false"
          namespaces:
            exclude:
            - akkeris-system
            - prometheus
            - cattle-prometheus
            - cattle-system
            - extrahop
            - sysdig-agent
