FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-openshift-4.6 AS builder
WORKDIR /go/src/sigs.k8s.io/descheduler
COPY . .
RUN go build -o descheduler ./cmd/descheduler

FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-base-openshift-4.6
COPY --from=builder /go/src/sigs.k8s.io/descheduler/descheduler /usr/bin/
CMD ["/usr/bin/descheduler"]
