name: manifests

on:
  pull_request:

jobs:
  deploy:
    strategy:
      matrix:
        k8s-version: ["v1.35.1"]
        descheduler-version: ["v0.35.0"]
        descheduler-api: ["v1alpha2"]
        manifest: ["deployment"]
        kind-version: ["v0.31.0"] # keep in sync with test/run-e2e-tests.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # git ls-remote https://github.com/actions/checkout.git refs/tags/v6.0.2
      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # git ls-remote https://github.com/helm/kind-action.git refs/tags/v1.14.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
          kubectl_version: ${{ matrix.k8s-version }}
          config: test/kind-config.yaml
          version: ${{ matrix.kind-version }}
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # git ls-remote https://github.com/actions/setup-go.git refs/tags/v6.4.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Build image
        run: |
          VERSION="dev" make dev-image
          docker tag descheduler:dev registry.k8s.io/descheduler/descheduler:${{ matrix.descheduler-version }}
      - name: Kind load image
        run: |
          kind load docker-image registry.k8s.io/descheduler/descheduler:${{ matrix.descheduler-version }} --name chart-testing
      - name: Create k8s manifests
        run: |
          kubectl create -f kubernetes/base/rbac.yaml
          kubectl create -f test/manifests/${{ matrix.descheduler-api }}/configmap.yaml
          kubectl create -f kubernetes/${{ matrix.manifest }}/${{ matrix.manifest }}.yaml
      - name: Wait for ready condition
        run: |
          kubectl wait --for=condition=Available --timeout=60s ${{ matrix.manifest }} descheduler -n kube-system
